### ISSUE TITLE
Autocompletion of functions is broken when passing func() as parameter

### ISSUE THREAD

**Issue by JohannWeging** [joefitzgerald/go-plus#172] opened 2015-03-17 01:03 UTC
The autocompletion is broken, when the function which is completed has a `func()` as parameter.

``` go
package main

// the parameter function takes an int and returns an int
func foo(bar func(a int) int) {}

func main() {
    // !ERROR!
    foo(bar func(a int)
}
```

The `funcRegex` doesn't handle the inner brackets and stops at the first `)` found.

**Comment by Matt3o12** [comment] 2015-03-21 20:12
I have a hard time understanding what the problem is.  
`func foo(func(a int) int)` doesn't make any sense to me. Did you mean `func foo(bar func(a int) int)`?

Furthermore, I don't know what autocomplete is supposed to do or what the error looks like.

**Comment by JohannWeging** [comment] 2015-03-22 00:34
Yes I mean `func foo(bar func(a int) int)`, updated the original post. Autocomplete should produce something along the line:
`foo(${1:bar func(a int) int})`

**Comment by bassu** [comment] 2015-04-08 03:49
This is very true. Completion is broken for functions which take functions as input. e.g. take http.HandleFunc method. Its completion definition shown is wrong.

![screen shot 2015-04-08 at 8 47 17 am](https://cloud.githubusercontent.com/assets/977697/7038486/ef36b332-ddcb-11e4-8aff-49b2ac395875.png)

**Comment by joefitzgerald** [comment] 2015-04-21 04:56
This is a problem related to the regex used to process the suggestion. In fact, this actually precludes the use of a regex because javascript regex's cannot use lookbehind. To fix this, we will need to write a custom parser that can count parenthesis.

**Comment by JohannWeging** [comment] 2015-04-21 12:22
Custom parser can be found in my original PR #114.

**Comment by zmb3** [comment] 2016-11-27 22:31
Fixed with https://github.com/joefitzgerald/autocomplete-go/commit/22374715c9feb3dad16428c13feff91d15f73b34

**Closed by zmb3** 2016-11-27 22:31 UTC
Labels: bug, priority
