### ISSUE TITLE
Clicking on compile errors to jump opens new file with several projects opened

### ISSUE THREAD

**Issue by otm** [joefitzgerald/go-plus#253] opened 2015-08-05 19:31 UTC
To reproduce:
1. Open go project
2. Right click tree view and choose "add project folder"
3. Open a second go project
4. Create a error like example error below. 
5. Click to error to jump to line

Expected result: 
Worker.go in second project is opened and highlighted line is 19

Actual result:
A new file, called worker.go, is opened in the first project.
 
Example error:
at line 19, character 1, file worker.go  comment on exported function ProcessMessages should be of the form "ProcessMessages ..."

**Comment by joefitzgerald** [comment] 2015-08-10 20:22
Duplicate of #243. As I articulated there, this is desirable, and will hopefully be fixed through integration with Linter.

**Closed by joefitzgerald** 2015-08-10 20:22 UTC
Labels: duplicate
