### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by peterwald** [joefitzgerald/go-plus#152] opened 2015-02-05 16:27 UTC
atom.services is no longer available. To register service providers and
consumers, use the `providedServices` and `consumedServices` fields in
your package's package.json.
```
Atom.Object.defineProperty.get (/usr/share/atom/resources/app/src/atom.js:64:11)
new Gocode (/home/peterwald/.atom/packages/go-plus/lib/gocode.coffee:13:25)
```

**Comment by joefitzgerald** [comment] 2015-02-05 16:39
Update your packages and Atom, and restart. Dupe of #151, #148, #147.

**Closed by joefitzgerald** 2015-02-05 16:39 UTC
Labels: duplicate
