### ISSUE TITLE
ctrl+click for godef

### ISSUE THREAD

**Issue by mahtuag** [joefitzgerald/go-plus#326] opened 2015-12-13 01:54 UTC
I'd like to be able to hold ctrl and click to invoke godef for whatever I clicked on. This would make go-plus feel similar to more "traditional" IDEs like Eclipse and IntelliJ which I am used to from my Java days in a past life :weary: 

Any idea how to achieve this ?

**Comment by maciejmrowiec** [comment] 2016-01-05 14:57
+1

**Comment by sagix** [comment] 2016-01-09 17:06
+1

**Comment by jims** [comment] 2016-02-28 20:17
+1

**Comment by tylerFowler** [comment] 2016-03-07 23:52
+1

**Comment by Depado** [comment] 2016-04-04 15:19
+1

**Comment by joefitzgerald** [comment] 2016-04-04 16:23
OK folks, I understand you want this. Please refrain from `+1` comments. Use the Thumbs up emoji on the original issue request.

This requires some work in the core of Atom. I will circle back on this issue and communicate timing once I've done some more investigation. The final combination may not be ctrl-click (e.g. it may be alt-click).

**Comment by zmb3** [comment] 2016-10-03 22:18
Closing as duplicate of #320

**Closed by zmb3** 2016-10-03 22:18 UTC
