### ISSUE TITLE
Code coverage 0.0% when tests are in *_test package

### ISSUE THREAD

**Issue by sisp** [joefitzgerald/go-plus#717] opened 2017-12-06 14:47 UTC
### Prerequisites

* [ ] Have you tried launching `atom .` from the terminal in your project's directory?
* [x] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [x] Have you updated Atom to the latest version?
* [ ] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [x] Have you updated your Atom packages to the latest versions?
* [x] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [x] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

I have a file ``file.go`` in the package ``pkg``and a test file ``file_test.go`` in the package ``pkg_test``. When I run tests on the commandline with ``go test -cover pkg`` I see the actual test coverage. In Atom, I get ``coverage: 0.0% of statements``. However, when I change the package of ``file_test.go`` to ``pkg``, I get the actual test coverage in Atom, too.

### Output from `atom -v && apm -v`

```
Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.6
git 1.9.1
```

### Output From `go env`

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/user/go"
GORACE=""
GOROOT="/usr/lib/go-1.9"
GOTOOLDIR="/usr/lib/go-1.9/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build639532777=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### Steps to Reproduce

See above.

### Expected Behavior

See actual code coverage in the go-plus outputs window.

### Actual Behavior

``coverage: 0.0% of statements``

**Comment by zmb3** [comment] 2017-12-09 20:17
I'm not able to reproduce:

![image](https://user-images.githubusercontent.com/7527103/33799161-1d88ca7c-dce3-11e7-9aeb-2aee86fa8776.png)

How did you install Go?  `/usr/lib/go-1.9` looks like a non-standard install.  Do you get the same results with the official binary distribution from golang.org?

**Comment by sisp** [comment] 2017-12-15 16:07
I'm using Ubuntu and followed the [instructions in the Go wiki](https://github.com/golang/go/wiki/Ubuntu).

**Comment by zmb3** [comment] 2018-02-12 04:32
@sisp could you also try with the official Go distribution and report whether the results are the same?

The wiki you referenced states:

> The Go project's official download page is at https://golang.org/dl/.
>
> There are some other options for Debian based systems like Ubuntu. These packages were not created by the Go project, and we don't support them, but they may be useful for you.

I'm not suggesting that things shouldn't work for you if you use another installation method, but the extra data point might help us to figure out what's going on.

**Comment by joefitzgerald** [comment] 2018-04-03 02:35
Closing this because we haven't seen a response, but feel free to reply with more detail and we can reopen it.

**Closed by joefitzgerald** 2018-04-03 02:35 UTC
Labels: waiting-response

**Comment by pizzalord22** [comment] 2018-10-01 08:36
"go test -cover" always returns 0% when the test files of a package are in an other directory then the tested files. even if everything is covered
