### ISSUE TITLE
Incorrect error line references with multiple Go projects open in a single window 

### ISSUE THREAD

**Issue by jpillora** [joefitzgerald/go-plus#364] opened 2016-02-19 06:18 UTC
When you have **multiple Go projects open in a single window**, the compile errors are always a relative path to the first project. For example, I have 3 projects open, there is a syntax error in the 3rd project:

![screen shot 2016-02-19 at 5 16 37 pm](https://cloud.githubusercontent.com/assets/633843/13168013/b1190482-d72c-11e5-9052-87cc7f2e8e1c.png)

And when I click it, it opens this path in the first project:

![screen shot 2016-02-19 at 5 16 50 pm](https://cloud.githubusercontent.com/assets/633843/13168014/b2aa19a8-d72c-11e5-8163-66ace9888e9a.png)

**Comment by technopoetic** [comment] 2016-02-19 18:27
I can corroborate this is happening.
Atom 1.2.4
Go-plus 3.5.3
Fedora 22 64 bit.

It works correctly when there's only one project folder, or when the offending project is the first project in the list.

**Comment by joefitzgerald** [comment] 2016-02-19 19:54
Acknowledged. This is an issue with atom-message-panel. This functionality is being replaced by [gometalinter-linter](https://atom.io/packages/gometalinter-linter), which is still alpha quality.

Duplicate of #328, #347.

**Closed by joefitzgerald** 2016-02-19 19:54 UTC
