### ISSUE TITLE
Atom Unable to install nfs gocode

### ISSUE THREAD

**Issue by Skybutter0** [joefitzgerald/go-plus#428] opened 2016-05-10 06:38 UTC
Running Ubuntu 16.04 LTS (Xenial Xerus) 64-bit
Issue on Atom 1.8.0 Beta3 and also Atom 1.7.3  

The atom editor is throwing the following error when attempting to run go get nfs/gocode: 
package github.com/nsf/gocode: cannot download, $GOPATH not set. For more details see: go help gopath

I have absolutely set the gopath in both bashrc and profile, as following post #386 

go env displays: 
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/userabc/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

**Comment by venatiodecorus** [comment] 2016-05-22 03:04
Atom has a problem reading environment variables. As a workaround, you can launch Atom from a terminal with:
`atom &`
That's been the best workaround I've found so far...

**Comment by joefitzgerald** [comment] 2016-05-22 14:15
https://github.com/joefitzgerald/go-plus/issues/386#issuecomment-199359955

The issue isn't with atom. The issue is that different files configure your windowing environment vs. your terminal environment. If you want particular env vars to be set for both scenarios (launching via the launcher, and launching via terminal) you need to take action to make them the same.

**Comment by djahma** [comment] 2016-05-22 22:51
I have this issue too, and it did not exist in whatever older version of atom + go-plus was up to date last year. It's only because atom embedded terminals are bridging the gap with sublimetext build system, that I've reopened and updated Atom.
The fact that go-plus settings accept a user entry for the GOPATH and then throw an error "GOPATH not set" is not serious. On top of that, talking about embedded terminals, terminal-plus uses the same environment as go-plus and typing the "env" command in there retrieves the GOPATH value...so the issue is with go-plus, and not atom indeed.

**Comment by joefitzgerald** [comment] 2016-05-23 03:50
go-plus no longer accepts user configuration of GOPATH. It must be set correctly in your environment. This is an issue with your environment. See the aforementioned comment on issue 386.

Terminal plus does not necessarily use the same environment as Atom itself. It is likely launching the shell (which would seem to be a necessity), so the environment seen there is not the same as the environment available to the JavaScript / NodeJS code that comprises atom. Open the chromium developer tools and type `process.env` to see for yourself.

**Comment by hardcoar** [comment] 2016-05-24 02:53
hi. im new to atom.

i followed instructions here: https://rominirani.com/setup-go-development-environment-with-atom-editor-a87a12366fcf

however i was not able to see go-plus in package list

**Comment by joefitzgerald** [comment] 2016-05-24 02:54
Those instructions were based on go-plus 3.5.x and are not valid for go-plus 4.x.x (they need to be updated). The "Go Plus" menu was renamed to "Go".

**Comment by hardcoar** [comment] 2016-05-24 03:26
i see. i have it now. thanks!

**Comment by djahma** [comment] 2016-05-26 22:02
fair enough, adding GOPATH to /etc/profile and restarting X does the trick.
I would wish go-plus to be more flexible though: being able to change GOPATH is tedious in this fashion. Could you make it possible to set GOPATH from within atom? (thinking of one GOPATH per project)

**Comment by joefitzgerald** [comment] 2016-05-26 22:26
You can absolutely change the GOPATH _very easily_. The solution is simple: launch atom from your terminal: `GOPATH=/some/path atom somedir` / `GOPATH=/some/otherpath atom someotherdir` and you get two windows with different GOPATHs.

**Comment by djahma** [comment] 2016-06-06 17:19
you know this goes against UX paradigm whereby .desktop files are there to easily launch apps. Although easy to implement, you trick is a downer, I'd rather stick to 'closed source' sublime...

**Comment by joefitzgerald** [comment] 2016-10-01 06:59
This should now be fixed in versions of atom >= `v1.11.0-beta3` (i.e. currently @ https://atom.io/beta). It will soon be in the stable version of atom. At that time, most users' frustrations with their environment _should_ be alleviated.

See https://github.com/atom/atom/pull/12562 for context.

**Closed by joefitzgerald** 2016-10-01 06:59 UTC
