### ISSUE TITLE
Lower case completion.

### ISSUE THREAD

**Issue by nmabhinandan** [joefitzgerald/go-plus#195] opened 2015-05-10 06:40 UTC
If there is an exposed function in a package like this,

```go
package Test
func TestFunc() {
  fmt.Print("asdf")
}
```

And if I try to access it like this,

```go
testF
```

The autocomplete shows the `TestFunc()` in autocompletion list, but it doesn't write out when I press Tab or Enter.

**Comment by joefitzgerald** [comment] 2015-05-15 03:51
Duplicate of #185. This is now bugging the hell out of me, so a fix is forthcoming soon!

**Comment by joefitzgerald** [comment] 2015-05-15 03:52
Duplicate of #185. This is now bugging the hell out of me, so a fix is forthcoming soon!

**Closed by joefitzgerald** 2015-05-15 03:52 UTC

**Comment by nmabhinandan** [comment] 2015-05-15 04:18
:+1:
