### ISSUE TITLE
cmd+click to go to source of function

### ISSUE THREAD

**Issue by rogierlommers** [joefitzgerald/go-plus#228] opened 2015-06-29 06:00 UTC
I recently switched from using LiteIDE to Atom (with go-plus) and I like it. However I miss one feature: the ability to cmd+click on a function which opens the source code from the corresponding package. See this recording to see what I mean: https://dl.dropboxusercontent.com/u/1757832/liteide-click-feature.mov After I cmd+click on the `.Handle()` function, it opens the `/net/http/server`-package. It would be great of you can add this missing feature to go-plus.

**Comment by peterbourgon** [comment] 2015-07-09 18:27
The behavior exists — put the cursor within the relevant symbol and type cmd + opt + g — but strong +1 to having a click handler. A must-have feature for me.

**Comment by billhsu** [comment] 2015-07-14 02:49
+1 for this

**Comment by codingrogue** [comment] 2015-08-01 19:20
+1

**Comment by leonardoeloy** [comment] 2015-08-07 16:58
:+1:

**Comment by Gurpartap** [comment] 2015-08-11 20:43
:+1: 

Atom currently does not support click bindings.

However, [nuclide-click-to-symbol](https://github.com/facebooknuclideapm/nuclide-click-to-symbol) plugin lets you provide this functionality via your own plugin (`go-plus` in our case).

The description of that plugin says they're working on adding this to Atom itself. Until, then maybe someone might want to take a crack at using this plugin.

**Comment by zmb3** [comment] 2016-10-03 22:20
Closing as duplicate of #320

**Closed by zmb3** 2016-10-03 22:20 UTC
