### ISSUE TITLE
OSX / AppEngine

### ISSUE THREAD

**Issue by tristancaron** [joefitzgerald/go-plus#223] opened 2015-06-26 10:08 UTC
Hello,

I had configured go-plus but, it doesn't work.

No Go Installations Were Found
Atom: 1.0.0 (darwin x64 14.3.0)

GOPATH = ~/google-cloud-sdk/platform/google_appengine/gopath
Go installation path = ~/google-cloud-sdk/google-cloud-sdk/bin/goapp

Thank you for your help.

**Comment by joefitzgerald** [comment] 2015-06-26 13:16
Duplicate of #76. I'm working on allowing different build tools to be used (i.e. to support gb), so the hooks will soon be there to support this.

**Closed by joefitzgerald** 2015-06-26 13:16 UTC
