### ISSUE TITLE
Crash on save

### ISSUE THREAD

**Issue by gregpechiro** [joefitzgerald/go-plus#432] opened 2016-05-25 16:34 UTC
Recently saving a go project can cause atom to crash. It seems to happen more when it needs to auto import something but it isn't limited to this. I'm not sure if it is the formatting or the linting. When I  save there is a long pause. After awhile I  get a message saying atom is not responding would I like to close or  wait. If I wait it still is frozen until the window pops up again asking what I would like to do. After I choose to close I get an output in my terminal where I had launched atom from. Here is what is displayed.

/usr/bin/atom: line 98:  4786 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
App load time: 2367ms
Failed to get crash dump id.
Report Id:

Let me know if there is any other information you need.

**Comment by joefitzgerald** [comment] 2016-05-25 16:52
Is this reproducible? Are you open to a screen sharing session to figure this out? If so, please join the `#go-plus` channel in one of these Slack teams, and then direct message me your email address:

[![Slack](https://img.shields.io/badge/atom_slack-%23go--plus-blue.svg?style=flat)](https://atom-slack.herokuapp.com) [![Slack](https://img.shields.io/badge/gophers_slack-%23go--plus-blue.svg?style=flat)](https://gophersinvite.herokuapp.com)

**Comment by Allendar** [comment] 2016-06-12 17:10
I'm experiencing this too but not as a full crash. It's just every like 3rd to 4th save it just fully dumps my code and empties my file. I'm not comfortable with this as, might something else happen and Atom crash afterwards it would mean _no undo possible_ and loss of all code until last commit, which is really uncomfortable.

Here's the error the console gives me on `console.log('gofmt: (stderr) ' + r.stderr)`:

```
gofmt: (stderr) /Users/erwin/Go/src/__Development/SAPI2/<standard input>:1:1: expected ';', found 'EOF'
/Users/erwin/Go/src/__Development/SAPI2/<standard input>:1:1: expected 'IDENT', found 'EOF'
/Users/erwin/Go/src/__Development/SAPI2/<standard input>:1:1: expected 'package', found 'EOF'
```

Maybe there's some kind of latency? It even happens with files that just have 20-50 lines. It happens in all my Go files, no recognizable pattern.

**Comment by joefitzgerald** [comment] 2016-06-12 19:02
@Allendar that sounds like a different issue. Would it be possible to do a screen sharing session with you? If so please use the links above and direct message me your email address.

**Comment by Allendar** [comment] 2016-06-12 19:11
Here's a small recording. I'm practically just saving at some different places and then you can see the content dropping paired with the error popup.

![untitled](https://cloud.githubusercontent.com/assets/5161272/15993307/0725d288-30e2-11e6-933f-fafaff505e92.gif)

**Comment by joefitzgerald** [comment] 2016-06-12 19:14
Disable all third party packages except `gofmt` and `go-config`. Let me know if it still occurs. Also, is there a networked filesystem in play here at all?

**Comment by Allendar** [comment] 2016-06-14 07:55
Sorry for my late response. Quite busy the last few days. Everything is on the MacBook's single-disk, so no network-FS' included. I tried with what you proposed and indeed nothing happened. I'll enable all packages one by one tonight and let you know what caused it. Got many different plugins for many languages installed so that might be causing havoc. Thanks for the feedback. I'll get back to you soon

**Comment by Allendar** [comment] 2016-06-14 07:57
Quick update: I think it's `atom-beautify`. I still have `gofmt` on in there with Beautify on Save. Seems to be fixed now with all other plugins on again.

**Comment by joefitzgerald** [comment] 2016-06-14 08:33
@gregpechiro do you also have atom-beautify installed and enabled? 

Glad you fracked this down @allendar!

**Comment by Allendar** [comment] 2016-06-14 08:39
The editor is also way more snappier now. You can actually see in the GIF screen-recording that the popup flashes often, fully halting the whole editor. I think the blank screen get's caused by by tools wanting to refactor the code and then (with some buffer?) bumping into each other, leaving a result thinking it was empty already, and putting the _empty_ code back in place. So if the beautifier runs first and then `go-plus` kicks in right after (or vice versa) one probably thinks the code was already empty and still parses it and puts the buffered refactored code back in place. Something like that :)

**Comment by gregpechiro** [comment] 2016-06-14 13:21
I do have atom-beautify installed I just disabled it. I will continue  to work on in Go today and let you know how it affects go-plus.

**Comment by gregpechiro** [comment] 2016-06-14 14:24
It seems to be an issue with goimports. I timed it on the command line and at one point it took just over 2 minutes. It's not very consistent either. After a little while it seems to respond quicker, but if I reboot my machine and try it, it acts really slow again. I will look into what the issue may be and comment here.

**Comment by seanchann** [comment] 2016-08-26 11:36
I have same issue . I configure a GOPATH on remote server by samba. when I save a file , atom will be crash.

**Comment by akutz** [comment] 2016-10-11 19:02
FYI, this is reproducible, but inconsistent. It is definitely to do with Goimports/Goreturns/Gometalinter. Check the CPU -- those procs are out of control when it happens (one of them anyway, sometimes more than one). It's a real PITA, but I'm attempting to live with it.

**Comment by akutz** [comment] 2016-10-11 19:03
And to @gregpechiro's comment, I do not have `atom-beautify` installed.

**Comment by joefitzgerald** [comment] 2016-10-11 19:07
When you say atom crashes; are you really saying it becomes unresponsive (resulting in you having to close the editor/atom)? We are running gofmt / goimports synchronously because the save API is synchronous, and they mutate the buffer. I can avoid this if I introduce a coordinator and be more explicit about the way the linter is invoked.

**Comment by akutz** [comment] 2016-10-11 19:10
Atom doesn't crash entirely, but a tab becomes unresponsive. What I do to clear it up is to open Activity Monitor and kill the spinning `gofmt`, `go-returns`, `go-imports`, or `gometalinter` process that is surely the reason behind it. When I kill one (or some or all) of those, the tab that was unresponsive "crashes" (it closes). I'm able to reopen it, usually with not much work lost. I almost always do a copy-all and paste into a blank file before saving a Go source file these days if I need or want to enable one of the aforementioned, offending tools for some reason.

**Comment by gregpechiro** [comment] 2016-10-11 19:12
For me the entire window would lock up the force close. Since the issue I was having definitely was my install and not the plug in I was able to find a work around. It's odd I know. When I save, as soon as after the window stops responding I switch atom out of view. Like display the desktop or something. Then I bring up a shell in the same directory I am working in. I run goimports . It can take up to 2 mins sometimes. After it finishes I switch back to atom and it is fine.

**Comment by zmb3** [comment] 2016-10-11 19:13
@akutz have you run `golang:update tools` just to rule out an outdated tool?

**Comment by akutz** [comment] 2016-10-11 19:19
@zmb3 I have not. I am keeping `glide` at the 0.11 version for various reasons, but that shouldn't be at fault in this case. I'll attempt the update. Thanks!

**Comment by akutz** [comment] 2016-10-11 19:20
@gregpechiro I haven't tried running those tools externally when the event occurs. I may try that next time.

Specifically the `go-imports` tool -- I wonder if any of these tools are being impacted by Go 1.7's stripping of unused code paths...

**Comment by akutz** [comment] 2016-10-11 19:22
Hi @zmb3,

I swear I'm not a Go newbie, but I just realized I don't know how to execute the suggested `golang:update tools` command. It clearly isn't a CLI command, so I googled it and did not find any telling reference. Could you shed some light on this? Thank you again!

**Comment by gregpechiro** [comment] 2016-10-11 19:23
@akutz not sure. I when I first experienced the issue I was on go 1.5.1. Lately I have been coding on a different machine with a fresh OS and go install. I don't have the issue on the new machine

**Comment by zmb3** [comment] 2016-10-11 19:28
@akutz Sorry, that's not a Go command, its an Atom command.  Easiest way is probably just to search for it from the command palette (cmd+shift+p on macOS).

**Comment by akutz** [comment] 2016-10-11 19:31
Hi @zmb3,

Ah, thanks! Running now :) Received this note -- an odd color choice if there is no error...

![image](https://cloud.githubusercontent.com/assets/101085/19285393/6a4bd4de-8fbf-11e6-8344-d2376ec85964.png)

**Comment by akutz** [comment] 2016-10-11 19:33
Hi @zmb3,

I just executed it again after failing to receive any feedback that it completed and this time the following windows appeared:

![image](https://cloud.githubusercontent.com/assets/101085/19285469/9a4a9490-8fbf-11e6-83f3-45205fcd6344.png)

**Comment by akutz** [comment] 2016-10-11 19:35
Thanks for the help everyone -- I will ping this thread again if the issue should reoccur post-tool update.

**Comment by zmb3** [comment] 2017-02-12 01:37
Haven't seen any activity in months, so assuming you're all set.  Feel free to file a new issue if you run into problems.

**Closed by zmb3** 2017-02-12 01:37 UTC
