### ISSUE TITLE
(Feature) `go run` current file from pane

### ISSUE THREAD

**Issue by kieraneglin** [joefitzgerald/go-plus#608] opened 2017-03-28 02:48 UTC
### Description

I just started learning Go this week, so if I have a fundamental misunderstanding of what I'm asking, please let me know :)

For simple projects I think it'd be handy to have a pane for go-plus that allows you to set parameters and `go run` the file on click and see the output from within go-plus.  

If there's interest in this, I could probably whip something together and make a PR.

**Comment by zmb3** [comment] 2017-03-28 04:02
I'm personally hesitant to add such a feature as 'go run file.go' only works if your package main is a single file. For packages any larger than that, you'll get a compiler error that will probably confuse new users more than having the feature would help them.

**Comment by kieraneglin** [comment] 2017-03-28 05:15
Fair enough!  In the real Go world, would you say most projects have a more complex hierarchy?  A very large percentage of projects I see on /r/golang have a huge amount of functions contained in a singe file which, while probably a product of bad project structure, would seem to benefit from an addition like this.

Again, I'm spitballing and my knowledge of the Go [blagosphere](https://xkcd.com/181/) is weak :)

**Comment by lloiser** [comment] 2017-03-28 06:15
duplicate of #154.

**Comment by kieraneglin** [comment] 2017-03-28 06:48
@lloiser, my apologies.  Would you still be accepting a PR on the matter?

**Comment by zmb3** [comment] 2017-10-22 00:17
Closing at dup.

**Closed by zmb3** 2017-10-22 00:17 UTC
