### ISSUE TITLE
Only enable these plugins in go files

### ISSUE THREAD

**Issue by rumpelsepp** [joefitzgerald/go-plus#490] opened 2016-10-17 08:13 UTC
Is it possible to enable these plugins only for go files? I often edit files in multiple languages; these go commands are useless in, let's say, python files. My atom starts to get bloated because every package is enabled in every file. :/

**Comment by joefitzgerald** [comment] 2016-12-19 18:41
Closing as duplicate of #77.

**Closed by joefitzgerald** 2016-12-19 18:41 UTC
