### ISSUE TITLE
Support metalinter

### ISSUE THREAD

**Issue by santagada** [joefitzgerald/go-plus#280] opened 2015-09-16 13:30 UTC
go metalinter can run a bunch of linters in parallel, I guess it would be a nice addition to run it on save instead of only golint

repo for metalinter:
https://github.com/alecthomas/gometalinter

**Comment by zmb3** [comment] 2015-09-17 17:03
Duplicate of https://github.com/joefitzgerald/go-plus/issues/213

**Closed** 2015-09-17 17:47 UTC
Labels: duplicate
